version: 2.1

orbs:
  python: circleci/python@0.2.1

executors:
  python-multiple:
    docker:
      - image: fkrull/multi-python

jobs:
  build-and-test:
    executor: python-multiple
    steps:
      - checkout
      #- python/load-cache
      - pip3 install -r requirements.txt
      #- python/save-cache
      - run:
          name: Run tests and coverage
          command: tox
      - run:
          name: Update coverage
          command: COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls

workflows:
  main:
    jobs:
      - build-and-test:
          context: checkenv
